/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_vanxum_Aic_OpusJni */

#ifndef _Included_com_vanxum_Aic_OpusJni
#define _Included_com_vanxum_Aic_OpusJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_vanxum_Aic_OpusJni
 * Method:    OpusInit
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_vanxum_Aic_OpusJni_OpusInit
  (JNIEnv *, jobject);

/*
 * Class:     com_vanxum_Aic_OpusJni
 * Method:    Opusdecode
 * Signature: ([B[SI)I
 */
JNIEXPORT jint JNICALL Java_com_vanxum_Aic_OpusJni_Opusdecode
  (JNIEnv *, jobject, jbyteArray, jshortArray, jint);

#ifdef __cplusplus
}
#endif
#endif
