/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_vanxum_Aic_NetworkJni */

#ifndef _Included_com_vanxum_Aic_NetworkJni
#define _Included_com_vanxum_Aic_NetworkJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_vanxum_Aic_NetworkJni
 * Method:    vmtlInit
 * Signature: (Ljava/lang/String;Ljava/lang/String;II)I
 */
JNIEXPORT jint JNICALL Java_com_vanxum_Aic_NetworkJni_vmtlInit
  (JNIEnv *, jobject, jstring, jstring, jint, jint,jint);

/*
 * Class:     com_vanxum_Aic_NetworkJni
 * Method:    startVmtl
 * Signature: (Z)I
 */
JNIEXPORT jint JNICALL Java_com_vanxum_Aic_NetworkJni_startVmtl
  (JNIEnv *, jobject, jboolean);

JNIEXPORT void JNICALL Java_com_vanxum_Aic_NetworkJni_stopVmtl
        (JNIEnv *, jobject);

/*
 * Class:     com_vanxum_Aic_NetworkJni
 * Method:    sendInputEvent
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_vanxum_Aic_NetworkJni_sendInputEvent
  (JNIEnv *, jobject,jbyteArray, jint);

JNIEXPORT void JNICALL Java_com_vanxum_Aic_NetworkJni_sendExamPacket
(JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
